// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new greeter API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for greeter API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GreeterGetCityWeather(params *GreeterGetCityWeatherParams, opts ...ClientOption) (*GreeterGetCityWeatherOK, error)

	GreeterSayHello(params *GreeterSayHelloParams, opts ...ClientOption) (*GreeterSayHelloOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GreeterGetCityWeather greeter get city weather API
*/
func (a *Client) GreeterGetCityWeather(params *GreeterGetCityWeatherParams, opts ...ClientOption) (*GreeterGetCityWeatherOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGreeterGetCityWeatherParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Greeter_GetCityWeather",
		Method:             "GET",
		PathPattern:        "/v1/citys/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GreeterGetCityWeatherReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GreeterGetCityWeatherOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GreeterGetCityWeatherDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GreeterSayHello sends a greeting
*/
func (a *Client) GreeterSayHello(params *GreeterSayHelloParams, opts ...ClientOption) (*GreeterSayHelloOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGreeterSayHelloParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Greeter_SayHello",
		Method:             "POST",
		PathPattern:        "/v1/example/echo",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GreeterSayHelloReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GreeterSayHelloOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GreeterSayHelloDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
