// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wawa0210/go-grpc-journey/pkg/sdk/models"
)

// GreeterSayHelloReader is a Reader for the GreeterSayHello structure.
type GreeterSayHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GreeterSayHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGreeterSayHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGreeterSayHelloDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGreeterSayHelloOK creates a GreeterSayHelloOK with default headers values
func NewGreeterSayHelloOK() *GreeterSayHelloOK {
	return &GreeterSayHelloOK{}
}

/* GreeterSayHelloOK describes a response with status code 200, with default header values.

A successful response.
*/
type GreeterSayHelloOK struct {
	Payload *models.HelloworldHelloReply
}

func (o *GreeterSayHelloOK) Error() string {
	return fmt.Sprintf("[POST /v1/example/echo][%d] greeterSayHelloOK  %+v", 200, o.Payload)
}
func (o *GreeterSayHelloOK) GetPayload() *models.HelloworldHelloReply {
	return o.Payload
}

func (o *GreeterSayHelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HelloworldHelloReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGreeterSayHelloDefault creates a GreeterSayHelloDefault with default headers values
func NewGreeterSayHelloDefault(code int) *GreeterSayHelloDefault {
	return &GreeterSayHelloDefault{
		_statusCode: code,
	}
}

/* GreeterSayHelloDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GreeterSayHelloDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the greeter say hello default response
func (o *GreeterSayHelloDefault) Code() int {
	return o._statusCode
}

func (o *GreeterSayHelloDefault) Error() string {
	return fmt.Sprintf("[POST /v1/example/echo][%d] Greeter_SayHello default  %+v", o._statusCode, o.Payload)
}
func (o *GreeterSayHelloDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GreeterSayHelloDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
