// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wawa0210/go-grpc-journey/pkg/sdk/models"
)

// GreeterGetCityWeatherReader is a Reader for the GreeterGetCityWeather structure.
type GreeterGetCityWeatherReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GreeterGetCityWeatherReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGreeterGetCityWeatherOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGreeterGetCityWeatherDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGreeterGetCityWeatherOK creates a GreeterGetCityWeatherOK with default headers values
func NewGreeterGetCityWeatherOK() *GreeterGetCityWeatherOK {
	return &GreeterGetCityWeatherOK{}
}

/* GreeterGetCityWeatherOK describes a response with status code 200, with default header values.

A successful response.
*/
type GreeterGetCityWeatherOK struct {
	Payload *models.HelloworldCityWeatherResponse
}

func (o *GreeterGetCityWeatherOK) Error() string {
	return fmt.Sprintf("[GET /v1/citys/{name}][%d] greeterGetCityWeatherOK  %+v", 200, o.Payload)
}
func (o *GreeterGetCityWeatherOK) GetPayload() *models.HelloworldCityWeatherResponse {
	return o.Payload
}

func (o *GreeterGetCityWeatherOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HelloworldCityWeatherResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGreeterGetCityWeatherDefault creates a GreeterGetCityWeatherDefault with default headers values
func NewGreeterGetCityWeatherDefault(code int) *GreeterGetCityWeatherDefault {
	return &GreeterGetCityWeatherDefault{
		_statusCode: code,
	}
}

/* GreeterGetCityWeatherDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GreeterGetCityWeatherDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the greeter get city weather default response
func (o *GreeterGetCityWeatherDefault) Code() int {
	return o._statusCode
}

func (o *GreeterGetCityWeatherDefault) Error() string {
	return fmt.Sprintf("[GET /v1/citys/{name}][%d] Greeter_GetCityWeather default  %+v", o._statusCode, o.Payload)
}
func (o *GreeterGetCityWeatherDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GreeterGetCityWeatherDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
