// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/hello_world.proto

package helloworld

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/googleapis/google/api"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetCityWeatherRequest) Validate() error {
	return nil
}
func (this *CityWeatherResponse) Validate() error {
	return nil
}
func (this *HelloRequest) Validate() error {
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
